// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP4NwE2nvKwAo05_NMXkVgg8xP9xU2bzo',
    appId: '1:626763313305:android:a081683fb2d6f71a734808',
    messagingSenderId: '626763313305',
    projectId: 'login-flutter-app-b6b4d',
    storageBucket: 'login-flutter-app-b6b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk28_ekMSGJxekqG8i1ZvtoelKUwzB8_o',
    appId: '1:626763313305:ios:eef615583742a456734808',
    messagingSenderId: '626763313305',
    projectId: 'login-flutter-app-b6b4d',
    storageBucket: 'login-flutter-app-b6b4d.appspot.com',
    androidClientId: '626763313305-m2j5famsqqfu7mjlpv7sadhvk678bhpg.apps.googleusercontent.com',
    iosClientId: '626763313305-fgvmrl4i4okfhh8sgcm7k42lh4k6mhuj.apps.googleusercontent.com',
    iosBundleId: 'com.codingwitht.loginFlutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaPar8HQIyITImOO61csKEjoxPXRzdR4',
    appId: '1:626763313305:web:ebd9e0522ae3ca09734808',
    messagingSenderId: '626763313305',
    projectId: 'login-flutter-app-b6b4d',
    authDomain: 'login-flutter-app-b6b4d.firebaseapp.com',
    storageBucket: 'login-flutter-app-b6b4d.appspot.com',
  );

}